elastic/terranova

- terranova/binds.py
- terranova/commands.py
* Implement `reconfigure`, `migrate-state`, and `upgrade` flags on init command.
* Let the user decide what to do instead of auto-reconfiguring the backend.
> feat: let the user decide

- terranova/commands/__init__.py
- terranova/commands/binds.py
- terranova/commands/helpers.py
- terranova/resources.py
- terranova/terranova.py
* Better implementation for selector.
* Native implementation using click param.
* Pre-requirement to implement selectors for taint and untaint commands.
* This will allow to implement secret rotation strategy implicitly.
> refactor: implement selectors at finder level

- .gitignore
- poetry.lock
- pyproject.toml
- scripts/env.py
- scripts/utils.py
- terranova/binds.py
- terranova/commands/binds.py
- terranova/commands/helpers.py
- terranova/resources.py
- terranova/utils.py
* Add support for pyright static checker.
* Auto generate pyright config file based on poetry venv.
* Make checker happy.
* Enable support for Zed IDE users.
* Enforce better code practices.
* Ability to detect early bugs.
> feat: support for pyright

- README.md
* Improve README layout.
* Better documentation and visibility.
> docs: improve readme layout

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Use Ephemeral GitHub tokens with a TTL of 30 minutes.
Requires further changes in the specific permissions set
> github-action: use ephemeral github token

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/env-install/action.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
* Add dependabot configuration.
* Rename env-setup action to env-install. 
* Help to keep dependencies up-to-date.
> ci: add dependabot to maintain dependencies up-to-date

- terranova/binds.py
- terranova/commands/binds.py
* Add input option for plan command.
* Add compact warnings option for plan command.
* Add no-color option for plan command.
* Add parallelism option for plan command.
* Support more native options for plan command.
> feat: forward more plan options

- terranova/binds.py
- terranova/commands/binds.py
* Support no backend flag on init command.
* It's useful to disable backend configuration within the CI.
> feat: support no backend on init command

- scripts/build.py
- scripts/generate.py
- scripts/lint.py
- scripts/release.py
- scripts/utils.py
* Detect tool dependencies before using them.
* We could get a stacktrace if one of the dependencies isn't detected.
> build: detect tools before using them

- README.md
- Add documentation about terranova install using brew.
- More option for installation.
> feat: brew install option

- .gitignore
- README.md
- terranova/resources.py
- terranova/templates/resources.md
* Implement metadata layer for data sources.
Closes #40
> feat: implement metadata support for data sources

- .zed/settings.json
* Specific local configuration for Zed IDE.
* Avoid re-format on each save.
> chore: don't format on save

- terranova/commands/binds.py
Part of https://github.com/elastic/terranova/issues/38
> feat(flag): support `--fail-at-end` flag

- terranova/binds.py
- terranova/commands/binds.py
- terranova/terranova.py
- Implement untaint command
- terraform supports it
> feat: implement bind for untaint command

- terranova/commands/binds.py
- terranova/terranova.py
- Add list command support
- List al resource groups.
Closes #51
> feat: add command list support

- .github/CODEOWNERS
- Add me in CODEOWNERS.
- I'm not part of the oblt-ci team anymore.
> feat: add amannocci in codeowners

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- scripts/build.py
- scripts/env.py
- scripts/release.py
- scripts/utils.py
- Remove toml and dotty dependencies
- Use poetry directly to retrieve the project version.
- Add pre-commit auto-update in the project upgrade task.
- Improve zed integration.
- Improve dev workflow.
> feat: improve dev workflow

- .github/workflows/ci.yml
- .github/workflows/env-install/action.yml
- poetry.lock
- poetry.toml
- pyproject.toml
- scripts/generate.py
- terranova.spec
- Update pyproject and isolate dependency groups.
- Minimize dependencies to analyze by pyinstaller.
- Remove env:configure dependency in all tasks.
- Reduce build time for pyinstaller.
- Avoid unneeded dependencies in the generated binary.
> feat: improve binary generation

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been deprecated in favor of 
https://github.com/elastic/oblt-actions.
If there are any questions, please reach out to the @elastic/observablt-ci
> github-action: use oblt-actions/git/setup

- terranova/binds.py
- terranova/commands/binds.py
- Support terranova plan generation.
- Support applying terranova plan
- Allow us to generate one terranova plan and apply it across group resources.
> feat: support plan generation

- .github/workflows/pre-release.yml
Fixes https://github.com/elastic/terranova/actions/runs/11497210829/job/32000441353#step:6:25
> Fix pre-release.yml

- .github/workflows/pre-release.yml
Fixes https://github.com/elastic/terranova/actions/runs/11497585421/job/32001583792#step:6:23
> Fix pre-release.yml (#105)

- scripts/generate.py
- terranova.spec
- Don't exclude mandatory modules.
- Generate binary correctly.
> fix: correctly generate binary

- terranova/commands/helpers.py
- Correct plan generation
- Correct plan/apply logic
> fix: correct plan generation

- terranova/binds.py
- Terminate properly managed process.
- The process was only killed by the supervisor.
> fix: terminate properly process

- terranova/binds.py
- Avoid sleeping 10s to handle graceful shutdown.
- We were waiting for 10s, even if the process was already terminated.
> fix: improve graceful termination

- uv.lock
<Actions>
<action id="3101a1a4f82bdd7612429a77bd755ec794788940c76dfaf6dd868673b7dd0004">
<h3>Update uv lock dependencies</h3>
<details id="4c512294ba0e29ec8632db3eb26408aff0db6be5b48b818a66416bbca94a0cf8">
<summary>Update uv lock file</summary>
<p>ran shell command &#34;uv lock -U&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via <a href="https://www.updatecli.io/docs/prologue/quick-start/">its manifest(s)</a>.</p>
<ul>
<li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pull request and delete the base …
> build: update all dependencies

- .github/updatecli/updatecli.d/updatecli.yml
- .github/updatecli/values.d/scm.yml
- Detect correctly updatecli changes.
- The PR isn't created at the moment.
> fix: detect uv.lock changes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- Add pull request and issue templates.
- Organize issues and pull requests.
> ci: use pr and issue templates

- scripts/generate.py
- terranova/resources.py
- terranova/schemas/manifest_schema_v1.3.json
- Make runbook env optional if needed.
- Unblock ability to create runbook with optional env vars.
> feat: add optional env for runbooks

- pyproject.toml
- Use uv build backend instead of hatchling
- Use uv tool chain for everything
CI
> build: use uv build backend

- terranova/binds.py
- Forward GCP env vars to terraform.
- The terraform provider can rely on implicit GCP env vars. 
Closes #237
> feat: forward gcp env vars
